### ISSUE TITLE
Auto Complete is not working

### ISSUE THREAD

**Issue by muhssamy** [gbrueckl/FabricStudio#1]
Could you please help me troubleshoot this 
![image](https://github.com/user-attachments/assets/59a9822e-7d01-4cee-a59a-c43b44c72940)

**Comment by gbrueckl** [comment]
I am still waiting for an official API definition from the MS team in form of a Swagger.json file. Once this is in place I will be able to provide Auto-completion here.

This is a known issue and will be fixed soon

Until then you will need to write the API  URL manually

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: muhssamy ***@***.***>
Sent: Sunday, July 28, 2024 12:19:51 AM
To: gbrueckl/FabricStudio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbrueckl/FabricStudio] Auto Complete is not working (Issue #1)


Could you please help me troubleshoot this
image.png (view on web)<https://github.com/user-attachments/assets/59a9822e-7d01-4cee-a59a-c43b44c72940>

**Comment by muhssamy** [comment]
thanks for your support
