### ISSUE TITLE
Extension does not show up after installation

### ISSUE THREAD

**Issue by thewilq** [gbrueckl/FabricStudio#2]
![image](https://github.com/user-attachments/assets/33a6fb78-99b8-43ae-ba14-fef4f7ec660b)
![image](https://github.com/user-attachments/assets/adddddc5-d5df-42e5-940b-1c90796afa4d)
![image](https://github.com/user-attachments/assets/121c647b-5ebc-41c1-ae7f-5852c70d5759)

**Comment by thewilq** [comment]
nevermind, found the solution on my own screenshot

**Comment by gbrueckl** [comment]
may I still ask what the issue was?

**Comment by thewilq** [comment]
Somehow I clicked that I do not trudst the workspace in vscode. So
extensions were disabled.

pt., 6 wrz 2024, 11:41 użytkownik Gerhard Brueckl ***@***.***>
napisał:
