### ISSUE TITLE
Extension update run forever

### ISSUE THREAD

**Issue by muhssamy** [gbrueckl/FabricStudio#3]
i am facing one problem that the new update is not installing it continue run forever. is there anything i should do? or this is a bug

**Comment by muhssamy** [comment]
i tried to install it via vsix and it succussed

**Comment by gbrueckl** [comment]
I am not aware of any issues nor did anything particular with regards to the installation process change
some features got added but no core functionalities got modified.
I would assume some temporary issue on your side? Have you tried restarting VSCode before installing the extension? (should not be necessary but just in case)

**Comment by gbrueckl** [comment]
closing due to no further feedback
